language: node_js
node_js:
  - 13
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgres
before_script:
  - psql -c "CREATE DATABASE expenses_test;" -U postgres
  - psql -c "CREATE USER 'robben' WITH PASSWORD 'password';" -U postgres
  - npm install -g sequelize-cli
script:
  - npm run test
